import type {GetServerSideProps, NextPage} from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className="container py-4">
      <Head>
        <title>BigCommerce + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="pb-3 mb-4 border-bottom">
        <Link href="/" passHref>
          <a className="d-flex align-items-center text-dark">
            <span className="fs-5 fw-bolder">Home</span>
          </a>
        </Link>
      </header>

      <div className="p-5 mb-4 bg-light rounded-3">
        <div className="container-fluid py-5">
          <h1 className="display-5 fw-bold">BigCommerce + Next.js</h1>
          <p className="col-md-8 fs-4">
            This is a server-side rendered example of Next.js using BigCommerce to provide
            e-commerce functionality.
          </p>
          <Link href="/" passHref>
            <a className="btn btn-dark btn-lg" type="button">
              View Products
            </a>
          </Link>
        </div>
      </div>

      <div className="row align-items-md-stretch">
        <div className="col-md-6">
          <div className="h-100 p-5 text-white bg-dark rounded-3">
            <h2>Don&apos;t Buy Things!</h2>
            <p>
              This is just an example website for testing. Do not buy anything you see on this
              website.
            </p>
            <Link href="/" passHref>
              <a className="btn btn-light" type="button">
                View Products
              </a>
            </Link>
          </div>
        </div>
        <div className="col-md-6">
          <div className="h-100 p-5 bg-light rounded-3">
            <h2>Don&apos;t Buy Things!</h2>
            <p>
              AGAIN, this is just an example website for testing. Do not buy anything you see on
              this website.
            </p>
            <Link href="/" passHref>
              <a className="btn btn-dark" type="button">
                View Products
              </a>
            </Link>
          </div>
        </div>
      </div>

      <footer className="pt-3 mt-4 text-muted d-flex justify-content-between border-top">
        <div>
          Created by{' '}
          <a
            className="text-muted"
            href="https://github.com/matthewvolk"
            rel="noreferrer"
            target="_blank"
          >
            Matthew Volk
          </a>
        </div>
        <div>&copy; 2021</div>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async context => {
  return {
    props: {}, // will be passed to the page component as props
  };
};

export default Home;
